services:
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub-${BUILD_NUMBER:-default}
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 1s
      timeout: 30s
      retries: 30
    networks:
      - selenium-network
  chrome-node:
    image: selenium/node-chrome:4.15.0
    container_name: chrome-node-${BUILD_NUMBER:-default}
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-network

networks:
  selenium-network:
    name: selenium-network-${BUILD_NUMBER:-default}
    driver: bridge