version: "3.9"
name: jenkins-set

volumes:
  jenkins-docker-certs:
  jenkins-home:

networks:
  jenkins-network:
    driver: bridge

services:
  jenkins:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: jenkins-master
    restart: unless-stopped
    networks:
      - jenkins-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
      JENKINS_OPTS: "--prefix="
    user: root
    volumes:
      - jenkins-home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
      - /var/run/docker.sock:/var/run/docker.sock
